cp _common.txt ag_crossfire_detail.txt
cp _common.txt ag_hidden_lab_detail.txt
cp _common.txt boot_camp_detail.txt
cp _common.txt bounce_detail.txt
cp _common.txt c0a0_detail.txt
cp _common.txt c0a0a_detail.txt
cp _common.txt c0a0b_detail.txt
cp _common.txt c0a0c_detail.txt
cp _common.txt c0a0d_detail.txt
cp _common.txt c0a0e_detail.txt
cp _common.txt c1a0_detail.txt
cp _common.txt c1a0a_detail.txt
cp _common.txt c1a0b_detail.txt
cp _common.txt c1a0c_detail.txt
cp _common.txt c1a0d_detail.txt
cp _common.txt c1a0e_detail.txt
cp _common.txt c1a1_detail.txt
cp _common.txt c1a1a_detail.txt
cp _common.txt c1a1b_detail.txt
cp _common.txt c1a1c_detail.txt
cp _common.txt c1a1d_detail.txt
cp _common.txt c1a1f_detail.txt
cp _common.txt c1a2_detail.txt
cp _common.txt c1a2a_detail.txt
cp _common.txt c1a2b_detail.txt
cp _common.txt c1a2c_detail.txt
cp _common.txt c1a2d_detail.txt
cp _common.txt c1a3_detail.txt
cp _common.txt c1a3a_detail.txt
cp _common.txt c1a3b_detail.txt
cp _common.txt c1a3c_detail.txt
cp _common.txt c1a3d_detail.txt
cp _common.txt c1a4_detail.txt
cp _common.txt c1a4b_detail.txt
cp _common.txt c1a4d_detail.txt
cp _common.txt c1a4e_detail.txt
cp _common.txt c1a4f_detail.txt
cp _common.txt c1a4g_detail.txt
cp _common.txt c1a4i_detail.txt
cp _common.txt c1a4j_detail.txt
cp _common.txt c1a4k_detail.txt
cp _common.txt c2a1_detail.txt
cp _common.txt c2a1a_detail.txt
cp _common.txt c2a1b_detail.txt
cp _common.txt c2a2_detail.txt
cp _common.txt c2a2a_detail.txt
cp _common.txt c2a2b1_detail.txt
cp _common.txt c2a2b2_detail.txt
cp _common.txt c2a2c_detail.txt
cp _common.txt c2a2d_detail.txt
cp _common.txt c2a2e_detail.txt
cp _common.txt c2a2f_detail.txt
cp _common.txt c2a2g_detail.txt
cp _common.txt c2a2h_detail.txt
cp _common.txt c2a3_detail.txt
cp _common.txt c2a3a_detail.txt
cp _common.txt c2a3b_detail.txt
cp _common.txt c2a3c_detail.txt
cp _common.txt c2a3d_detail.txt
cp _common.txt c2a3e_detail.txt
cp _common.txt c2a4_detail.txt
cp _common.txt c2a4a_detail.txt
cp _common.txt c2a4b_detail.txt
cp _common.txt c2a4c_detail.txt
cp _common.txt c2a4d_detail.txt
cp _common.txt c2a4e_detail.txt
cp _common.txt c2a4f_detail.txt
cp _common.txt c2a4g_detail.txt
cp _common.txt c2a5_detail.txt
cp _common.txt c2a5a_detail.txt
cp _common.txt c2a5b_detail.txt
cp _common.txt c2a5c_detail.txt
cp _common.txt c2a5d_detail.txt
cp _common.txt c2a5e_detail.txt
cp _common.txt c2a5f_detail.txt
cp _common.txt c2a5g_detail.txt
cp _common.txt c2a5w_detail.txt
cp _common.txt c2a5x_detail.txt
cp _common.txt c3a1_detail.txt
cp _common.txt c3a1a_detail.txt
cp _common.txt c3a1b_detail.txt
cp _common.txt c3a2_detail.txt
cp _common.txt c3a2a_detail.txt
cp _common.txt c3a2b_detail.txt
cp _common.txt c3a2c_detail.txt
cp _common.txt c3a2d_detail.txt
cp _common.txt c3a2e_detail.txt
cp _common.txt c3a2f_detail.txt
cp _common.txt c4a1_detail.txt
cp _common.txt c4a1a_detail.txt
cp _common.txt c4a1b_detail.txt
cp _common.txt c4a1c_detail.txt
cp _common.txt c4a1d_detail.txt
cp _common.txt c4a1e_detail.txt
cp _common.txt c4a1f_detail.txt
cp _common.txt c4a2_detail.txt
cp _common.txt c4a2a_detail.txt
cp _common.txt c4a2b_detail.txt
cp _common.txt c4a3_detail.txt
cp _common.txt c5a1_detail.txt
cp _common.txt contamination_detail.txt
cp _common.txt crossfire_detail.txt
cp _common.txt cyanidestalkyard_detail.txt
cp _common.txt datacore_detail.txt
cp _common.txt disposal_detail.txt
cp _common.txt doublecross_detail.txt
cp _common.txt echo_detail.txt
cp _common.txt endcamp_detail.txt
cp _common.txt frenzy_detail.txt
cp _common.txt gasworks_detail.txt
cp _common.txt hldemo1_detail.txt
cp _common.txt hldemo2_detail.txt
cp _common.txt hldemo3_detail.txt
cp _common.txt lambda_bunker_detail.txt
cp _common.txt lost_village2_detail.txt
cp _common.txt pool_party_detail.txt
cp _common.txt rapidcore_detail.txt
cp _common.txt rebellion_detail.txt
cp _common.txt rocket_frenzy_detail.txt
cp _common.txt rustmill_detail.txt
cp _common.txt scary_1_detail.txt
cp _common.txt snark_pit_detail.txt
cp _common.txt stalkx_detail.txt
cp _common.txt stalkyard_detail.txt
cp _common.txt subtransit_detail.txt
cp _common.txt t0a0_detail.txt
cp _common.txt t0a0a_detail.txt
cp _common.txt t0a0b_detail.txt
cp _common.txt t0a0b1_detail.txt
cp _common.txt t0a0b2_detail.txt
cp _common.txt t0a0c_detail.txt
cp _common.txt t0a0d_detail.txt
cp _common.txt thunderstruck_detail.txt
cp _common.txt undertow_detail.txt
cp _common.txt xen_dm_detail.txt
